name: example
publish_to: none
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  freezed_factories:
    path: ../
  freezed_annotation: ^2.4.4
  faker: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  lints: ^4.0.0
  test: ^1.24.0
