builders:
  freezed_factories:
    import: "package:freezed_factories/builder.dart"
    builder_factories: [ "factoryBuilder" ]
    build_extensions: { ".dart": [ ".factory.dart" ] }
    auto_apply: dependents
    build_to: source
targets:
  $default:
    builders:
      freezed_factories:
        generate_for:
          - test/src/*.dart
