name: freezed_factories
description: "Create test factories for your Freezed classes easily"
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  source_gen: ^1.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.13
  freezed_annotation: ^2.4.4
  lints: ^5.0.0
  source_gen_test: ^1.1.1
  test: ^1.24.0
