name: freezed_factories_annotation
description: Annotations for freezed_factories.
version: 3.0.0
repository: https://github.com/idoctus/freezed_factories
issue_tracker: https://github.com/idoctus/freezed_factories/issues

environment:
  sdk: ">=3.8.1 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
