name: freezed_factories_example
publish_to: none
description: Example on how to use freezed_factories
version: 1.1.0

environment:
  sdk: ^3.6.0

dependencies:
  freezed_factories:
    path: ../
  freezed_factories_annotation:
    path: ../../freezed_factories_annotation
  freezed_annotation: ^3.0.0
  faker: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^3.0.4
  lints: ^5.1.1
  test: ^1.25.14

dependency_overrides:
  freezed_factories:
    path: ../
  freezed_factories_annotation:
    path: ../../freezed_factories_annotation
