name: freezed_factories_example
publish_to: none
description: Example on how to use freezed_factories
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  freezed_factories:
    path: ../
  freezed_factories_annotation:
    path: ../../freezed_factories_annotation
  freezed_annotation: ^2.4.4
  faker: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  lints: ^5.0.0
  test: ^1.24.0
