name: freezed_factories
description: "Create test factories for your Freezed classes easily"
version: 2.0.0
repository: https://github.com/idoctus/freezed_factories
issue_tracker: https://github.com/idoctus/freezed_factories/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ^7.3.0
  build: ^2.4.2
  source_gen: ^2.0.0
  freezed: ^3.0.0
  freezed_factories_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  lints: ^5.1.1
  freezed_annotation: ^3.0.0
  source_gen_test: ^1.1.1
  test: ^1.25.14
