name: freezed_factories
description: "Create test factories for your Freezed classes easily"
version: 1.0.0-dev.1
repository: https://github.com/idoctus/freezed_factories
issue_tracker: https://github.com/idoctus/freezed_factories/issues

environment:
  sdk: ^3.6.0

dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  source_gen: ^1.5.0
  freezed_factories_annotation: ^1.0.0-dev.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed_annotation: ^2.4.4
  lints: ^5.0.0
  source_gen_test: ^1.1.1
  test: ^1.24.0
