name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  general:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./freezed_factories

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.6.0"

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Check Formatting
        run: dart format --line-length 80 --set-exit-if-changed $(find lib test -name '*.dart' -not -name 'generate_example_golden.dart')

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test

  example:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: ./freezed_factories/example

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.6.0"

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Build
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: dart test
