name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  general:
    runs-on: ubuntu-latest

    container:
      image:  dart:stable

    steps:
      - uses: actions/checkout@v4

      - name: Print Dart SDK version
        run: dart --version

      - name: Change directory to freezed_factories
        run: cd freezed_factories

      - name: Install dependencies
        run: dart pub get

      - name: Check Formatting
        run: dart format --line-length 80 --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Run tests
        run: dart test

  example:
    runs-on: ubuntu-latest

    container:
      image:  dart:stable

    steps:
      - uses: actions/checkout@v4

      - name: Print Dart SDK version
        run: dart --version

      - name: Change directory to freezed_factories/example
        run: cd freezed_factories/example

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
